# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{divshare}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Watson"]
  s.date = %q{2009-11-19}
  s.description = %q{divshare
========

Description
-----------

The divshare gem makes it easier to use the Divshare API. To use it, you need
to create a Divshare account and sign up for an API key.

Usage
-----

Here's a brief walkthrough of the basic operations (see `examples/` for more information):

    require 'divshare'

    # Set these for your divshare account
    api_key    = 'your api key'
    api_secret = 'your api secret'
    email      = 'your login email address'
    password   = 'your password'
    filename   = 'a file you want to upload'

    client = Divshare::Client.new(api_key, api_secret)
    client.login(email, password)
    all_my_files = client.get_user_files
    all_my_files.each do |f| 
      print "#{f.file_name} (#{f.file_size}) "
      puts "was last downloaded #{Time.at(f.last_downloaded_at.to_i)}"
    end
    ticket = client.get_upload_ticket
    uploaded_id = client.upload(ticket, filename)
    puts "#{filename} uploaded with new id: #{uploaded_id}"
    client.logout

Now, going through the same script step-by-step. Use your Divshare API
key and secret (comes with key) to create a client:

    client = Divshare::Client.new(api_key, api_secret)
    
Login using the credentials for your Divshare account:

    client.login(email, password)

Get an array of all of your files:

    all_my_files = client.get_user_files
    
Do something with the files:

    all_my_files.each do |f| 
      print "#{f.file_name} (#{f.file_size}) "
      puts "was last downloaded #{Time.at(f.last_downloaded_at.to_i)}"
    end

Upload a file, and capture its id:

    ticket = client.get_upload_ticket
    uploaded_id = client.upload(ticket, filename)

Logout

    client.logout

Installation
------------

Install using rubygems:

    sudo gem install divshare 

Or clone from github
    
    git clone git://github.com/wasnotrice/divshare.git}
  s.email = %q{wasnotrice@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/divshare.rb",
     "lib/divshare/client.rb",
     "lib/divshare/divshare_file.rb",
     "lib/divshare/encoder.rb",
     "lib/divshare/errors.rb",
     "lib/divshare/multipart.rb",
     "lib/divshare/user.rb"
  ]
  s.homepage = %q{http://github.com/wasnotrice/divshare}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{divshare}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby interface to the DivShare file hosting service}
  s.test_files = [
    "spec/client_spec.rb",
     "spec/divshare_file_spec.rb",
     "spec/encoder_spec.rb",
     "spec/spec_helper.rb",
     "spec/user_spec.rb",
     "examples/example.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 1.16"])
    else
      s.add_dependency(%q<hpricot>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 1.16"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 1.16"])
  end
end

