# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{divshare}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eric Watson"]
  s.date = %q{2009-11-10}
  s.description = %q{A Ruby interface to the DivShare file hosting service}
  s.email = %q{wasnotrice@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "lib/divshare.rb",
     "lib/divshare/client.rb",
     "lib/divshare/divshare_file.rb",
     "lib/divshare/encoder.rb",
     "lib/divshare/errors.rb",
     "lib/divshare/multipart.rb",
     "lib/divshare/user.rb"
  ]
  s.homepage = %q{http://github.com/wasnotrice/divshare}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{divshare}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby interface to the DivShare file hosting service}
  s.test_files = [
    "spec/client_spec.rb",
     "spec/divshare_file_spec.rb",
     "spec/encoder_spec.rb",
     "spec/spec_helper.rb",
     "spec/user_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
    else
      s.add_dependency(%q<hpricot>, [">= 0"])
      s.add_dependency(%q<mime-types>, [">= 0"])
    end
  else
    s.add_dependency(%q<hpricot>, [">= 0"])
    s.add_dependency(%q<mime-types>, [">= 0"])
  end
end

